SUPABASE_URI = "postgresql://postgres.qxtcftcdexrchqjoxxwk:Certiredes2027@aws-0-us-west-1.pooler.supabase.com:6543/postgres"
# (Aquí arriba está su SUPABASE_URI que ya teníamos)
TWILIO_TEMPLATE_SID = "HX8a0789521437fb76f489c025a2be5513"
TWILIO_ACCOUNT_SID = "ACe411b7d301357600771550712214d873"
TWILIO_AUTH_TOKEN = "2d61a1cac441faa69a34945eb0fe5854"
TWILIO_PHONE = "+15559416718"