SUPABASE_URI = "postgresql://postgres.jepgfqxeukmxjusctnut:Certiredes2027@aws-1-us-east-1.pooler.supabase.com:6543/postgres"

# (Aquí arriba está su SUPABASE_URI que ya teníamos)

TWILIO_ACCOUNT_SID = "ACe411b7d301357600771550712214d873"
TWILIO_AUTH_TOKEN = "ff5d7db6a64dda5e888b3b130d1a92db"
TWILIO_PHONE = "+15559416718"
TWILIO_TEMPLATE_SID = "HX8a0789521437fb76f489c025a2be5513"